config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :member, skip: [:passwords], controllers: {
    registrations: "public/members/registrations",
    sessions: 'public/members/sessions'
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get "/members/quit" => "members#quit"
    patch "/members/out" => "members#out"

    devise_scope :member do
      post "members/guest_sign_in" => "members/sessions#guest_sign_in"
    end

    resources :members, only: [:show, :edit, :update] do
      resources :contacts, only: [:new, :show, :create]
    end
    resources :campsites, only: [:index, :show] do
      resources :reviews, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :members, only: [:index, :show, :edit, :update]
    resources :campsites do
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    end
    resources :contacts, only: [:edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/campsite.rb
class Campsite < ApplicationRecord

  belongs_to :campsite_type
  belongs_to :prefecture
  has_many :reviews, dependent: :destroy

  has_one_attached :campsite_image
  has_one_attached :map_image
  has_one_attached :temperture_image

  validates :name, presence: true, length: {minimum: 5}
  validates :campsite_type_id, presence: true
  validates :prefecture_id, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, length: {minimum: 7}, numericality: { only_integer: true }
  validates :route, presence: true, length: {minimum: 10}
  validates :feature, presence: true, length: {minimum: 10}
  validates :considerations, presence: true, length: {minimum: 10}

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
end

app/models/campsite_type.rb
class CampsiteType < ApplicationRecord

  has_many :campsites, dependent: :destroy

  enum type_name:{
    "---":0,
    高原:1,海辺:2,河原:3,林間:4,湖畔:5
  }

end

app/controllers/admin/campsites_controller.rb
class Admin::CampsitesController < ApplicationController
  before_action :authenticate_admin!

  def new
    @campsite = Campsite.new
  end

  def index
    @prefectures = Prefecture.all
    @campsite_types = CampsiteType.all

    if params[:prefecture_id].present? && params[:campsite_type_id].present?
      @campsites = Campsite.where(prefecture_id: params[:prefecture_id], campsite_type_id: params[:campsite_type_id]).page(params[:page]).per(5)
    elsif params[:prefecture_id].present?
      @campsites = Campsite.where(prefecture_id: params[:prefecture_id]).page(params[:page]).per(5)
    elsif params[:campsite_type_id].present?
      @campsites = Campsite.where(campsite_type_id: params[:campsite_type_id]).page(params[:page]).per(5)
    else
      @campsites = Campsite.page(params[:page]).per(5)
    end
    respond_to do |format|
        format.html
        format.js
      end
  end

  def show
    @campsite = Campsite.find(params[:id])
    @tags = Tag.all
    @seasons = Season.all

    @content = params[:content]
    @method = params[:search_method]
    @season_id = params[:season_id]

    @reviews = Review.where(campsite_id: @campsite.id)

    if @season_id.present?
      @reviews = @reviews.where(season_id: @season_id)
    end

    if @content.present?
      tag_review_ids = Tag.search_reviews_for(@content, @method)
      review_ids = @reviews.pluck(:id) & tag_review_ids
      @reviews = Review.where(id: review_ids)
    end

    @reviews = @reviews.page(params[:page]).per(5)
    respond_to :html, :js
  end

  def edit
    @campsite = Campsite.find_by(id: params[:id])
    if @campsite.present?
    else
      redirect_to admin_path
    end
  end

  def create
    @campsite = Campsite.new(campsite_params)
    if @campsite.save
      redirect_to admin_campsites_path
    else
      render :new
    end
  end

  def update
    @campsite = Campsite.find(params[:id])
    if @campsite.update(campsite_params)
      redirect_to admin_campsite_path(@campsite)
    else
      render :edit
    end
  end

  def destroy
    campsite = Campsite.find(params[:id])
    campsite.destroy
    redirect_to admin_campsites_path
  end

  private

  def campsite_params
    params.require(:campsite).permit(
      :campsite_type_id,
      :prefecture_id,
      :name,
      :address,
      :phone_number,
      :route,
      :feature,
      :considerations,
      :campsite_image,
      :prefecture_name,
      :type_name,
      :latitude,
      :longitude
      )
  end
end

app/helpers/admin/campsites_helper.rb
module Admin::CampsitesHelper
end

app/views/admin/campsites/_index.html.erb
<div class="row">
  <div class="col">
    <table class="table table-hover">
      <thead>
        <tr class="text-center">
          <th>キャンプ場写真</th>
          <th>キャンプ場名</th>
          <th>キャンプ場種類</th>
          <th>レビュー数</th>
        </tr>
      </thead>
      <tbody>
        <% campsites.each do |campsite| %>
        <tr class="text-center">
          <td>
            <% if campsite.campsite_image.attached? %>
              <%= image_tag campsite.campsite_image, size: "100x100", class: "image-fit-sm" %>
            <% else %>
              <%= image_tag asset_path('no_image1.jpg'), size: "100x100" %>
            <% end %>
          </td>
          <td class="font-weight-bold align-middle">
            <%= link_to admin_campsite_path(campsite), class:"text-dark" do %>
              <%= campsite.name %>
            <% end %>
          </td>
          <td class="font-weight-bold align-middle"><%= campsite.campsite_type.type_name %></td>
          <td class="font-weight-bold align-middle"><%= campsite.reviews.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate campsites, remote: true %>
  </div>
</div>

app/views/admin/campsites/edit.html.erb
<div class="container mt-3 mb-3">
  <div class="row">
    <div class="col"></div>
    <div class="col-5">
      <h1>キャンプ場情報編集</h1>
      <% if @campsite.errors.any? %>
        <%= @campsite.errors.count %>件の記入ミスがあります
        <ul>
          <% @campsite.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with model: @campsite, url: admin_campsite_path do |f| %>
        <table class="table">
          <tr>
            <th class="border-0"><%= f.label :campsite_image, 'キャンプ場写真' %></th>
            <td class="border-0"><%= f.file_field :campsite_image, accept: "image/*" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :name, 'キャンプ場名' %></th>
            <td class="border-0"><%= f.text_field :name, class:"form-control form-control-sm align-middle", style:"width: 400px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :campsite_type_id, 'キャンプ場種類' %></th>
            <td class="border-0"><%= f.select 'campsite_type_id', options_for_select(CampsiteType.type_names.map {|key, value| [key, value]}), {}, class:"form-control form-control-sm align-middle text-center", style:"width: 70px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :prefecture_id, '県名' %></th>
            <td class="border-0">
              <%= f.select 'prefecture_id', options_for_select(Prefecture.prefecture_names.map {|key, value| [key, value]}), {}, class:"form-control form-control-sm align-middle text-center", style:"width: 100px;" %>
            </td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :address, 'キャンプ場住所' %></th>
            <td class="border-0"><%= f.text_area :address, class:"form-control form-control-sm align-middle", style:"width: 400px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :phone_number, '電話番号' %></th>
            <td class="border-0"><%= f.text_field :phone_number, class:"form-control form-control-sm align-middle", style:"width: 200px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :route, 'アクセス方法' %></th>
            <td class="border-0"><%= f.text_field :route, class:"form-control form-control-sm align-middle", style:"width: 400px; height: 50px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :feature, '特徴' %></th>
            <td class="border-0"><%= f.text_area :feature, class:"form-control form-control-sm align-middle", style:"width: 400px; height: 200px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :considerations, '注意事項' %></th>
            <td class="border-0"><%= f.text_area :considerations, class:"form-control form-control-sm align-middle", style:"width: 400px; height: 200px;" %></td>
          </tr>
          <tr>
            <td class="border-0"></td>
            <td class="border-0">
              <%= f.submit '変更保存', class: 'btn btn-success mr-4' %>
              <%= link_to "削除", admin_campsite_path(@campsite), method: :delete, class: "btn btn-danger", "data-confirm" => "レビューも削除されます。本当に削除しますか？" %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/campsites/index.html.erb
<div style="height: 800px;">
  <div class="container mt-3 mb-3">
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <h1>キャンプ場一覧</h1>
      </div>
      <div class="col">
        <%= link_to "キャンプ場新規登録", new_admin_campsite_path, class: 'btn btn-success' %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col">
        <div class="text-center mb-3">
          <%= form_with(url: admin_campsites_path, method: :get, data: {remote: true}) do |f| %>
            <span class="font-weight-bold mr-3">県名</span>
            <%= f.collection_select :prefecture_id, @prefectures, :id, :prefecture_name, { prompt: '選択' }, class: "form-control-sm", style:"width: 100px;" %>
            <span class="font-weight-bold ml-3 mr-3">キャンプ場種類</span>
            <%= f.collection_select :campsite_type_id, @campsite_types, :id, :type_name, { prompt: '選択' }, class: "form-control-sm", style:"width: 100px;" %>
            <%= f.submit '表示', class:"btn btn-primary ml-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container" id="campsite-list">
    <%= render 'admin/campsites/index', campsites: @campsites %>
  </div>
</div>

app/views/admin/campsites/index.js.erb
$("#campsite-list").html("<%= j(render 'admin/campsites/index', campsites: @campsites) %>")

app/views/admin/campsites/new.html.erb
<div class="container mt-3 mb-3">
  <div class="row">
    <div class="col-3"></div>
    <div class="col">
      <h1>キャンプ場新規登録</h1>
      <% if @campsite.errors.any? %>
        <%= @campsite.errors.count %>件の記入ミスがあります
        <ul>
          <% @campsite.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col">
      <%= form_with model: @campsite, url: admin_campsites_path, class: "form-row" do |f| %>
        <table class="table">
          <tr>
            <th class="border-0 col-2"><%= f.label :campsite_image, 'キャンプ場写真' %></th>
            <td class="border-0 col-5"><%= f.file_field :campsite_image, accept: "image/*" %></td>
            <td class="border-0 col-5"></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :name, 'キャンプ場名' %></th>
            <td class="border-0"><%= f.text_field :name, class:"form-control form-control-sm align-middle", style:"width: 400px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :address, 'キャンプ場住所' %></th>
            <td class="border-0"><%= f.text_area :address, class:"form-control form-control-sm align-middle", style:"width: 400px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :prefecture_id, '県名' %></th>
            <td class="form-group border-0">
              <%= f.select 'prefecture_id', options_for_select(Prefecture.prefecture_names.map {|key, value| [key, value]}), {}, class:"form-control form-control-sm align-middle text-center", style:"width: 100px;" %>
            </td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :campsite_type_id, 'キャンプ場種類' %></th>
            <td class="border-0"><%= f.select 'campsite_type_id', options_for_select(CampsiteType.type_names.map {|key, value| [key, value]}), {}, class:"form-control form-control-sm align-middle text-center", style:"width: 70px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :phone_number, '電話番号' %></th>
            <td class="border-0"><%= f.text_field :phone_number, class:"form-control form-control-sm align-middle", style:"width: 200px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :route, 'アクセス方法' %></th>
            <td class="border-0"><%= f.text_area :route, class:"form-control form-control-sm align-middle", style:"width: 400px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :feature, '特徴' %></th>
            <td class="border-0"><%= f.text_area :feature, class:"form-control form-control-sm align-middle", style:"width: 400px; height: 200px;" %></td>
          </tr>
          <tr>
            <th class="border-0"><%= f.label :considerations, '注意事項' %></th>
            <td class="border-0"><%= f.text_area :considerations, class:"form-control form-control-sm align-middle", style:"width: 400px; height: 200px;" %></td>
          </tr>
          <tr>
            <td class="border-0"></td>
            <td class="border-0 text-center"><%= f.submit '新規登録', class: 'btn btn-lg btn-success' %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/campsites/show.html.erb
<div class="container mt-3 mb-3">
  <div class="row">
    <div class="col">
      <span class="h1"><%= @campsite.name %></span>
    </div>
    <div class="col-2">
      <%= link_to "編集する", edit_admin_campsite_path(@campsite), class: "btn btn-success" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-2">
      <% if @campsite.campsite_image.attached? %>
        <%= image_tag @campsite.campsite_image, size: "200x200", class: "image-fit" %>
      <% else %>
        <%= image_tag asset_path('no_image2.jpg'), size: "200x200" %>
      <% end %>
    </div>
    <div class="col-1"></div>
    <div class="col-8">
      <table class="table">
        <tr>
          <th class="border-0">種類</th>
          <td class="border-0"><%= @campsite.campsite_type.type_name %></td>
        </tr>
        <tr>
          <th class="border-0 col-4">県名</th>
          <td class="border-0"><%= @campsite.prefecture.prefecture_name %></td>
        </tr>
        <tr>
          <th class="border-0">住所</th>
          <td class="border-0"><%= @campsite.address %></td>
        </tr>
        <tr>
          <th class="border-0">電話番号</th>
          <td class="border-0"><%= @campsite.phone_number %></td>
        </tr>
        <tr>
          <th class="border-0">アクセス方法</th>
          <td class="border-0"><%= @campsite.route %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col text-center">
      <span class="h3">特徴</span>
      <p class="mt-2"><%= simple_format(@campsite.feature, class: "h4") %></p>
    </div>
    <div class="col text-center">
      <span class="h3">注意事項</span>
      <p class="mt-2"><%= simple_format(@campsite.considerations, class: "h4") %></p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col text-center">
      <div id="map" class="m-auto"></div>
      <script type="text/javascript">
        function initMap() {
          var test ={lat: <%= @campsite.latitude %>, lng: <%= @campsite.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 15,
                    center: test
                    });
          var transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);

          var contentString = '住所：<%= @campsite.address %>';
          var infowindow = new google.maps.InfoWindow({
            content: contentString
          });
          var marker = new google.maps.Marker({
                        position:test,
                        map: map,
                        title: contentString
                      });

          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });
        }
      </script>
      <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap"></script>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col text-center">
      <%= form_with(url: admin_campsite_path(@campsite), method: :get, data: {remote: true, type: "script"}) do |f| %>
        <span class="font-weight-bold h4">季節</span>
        <%= f.collection_select :season_id, @seasons, :id, :season_name, { prompt: '選択' }, class: "form-control-sm", style:"width: 100px;" %>
        <span class="font-weight-bold ml-3 h4">タグ</span>
        <%= f.text_field :content, class:"form-control-sm align-middle text-center", style:"width: 100px;" %>
        <%= f.hidden_field :search_method, :value => "perfect" %>
        <%= f.submit 'レビュー検索', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container mt-3" id="admin-review-list">
  <%= render 'admin/reviews/index', reviews: @reviews, campsite: @campsite %>
</div>

app/views/admin/campsites/show.js.erb
$("#admin-review-list").html("<%= j(render 'admin/reviews/index', reviews: @reviews, campsite: @campsite) %>")