config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :member, skip: [:passwords], controllers: {
    registrations: "public/members/registrations",
    sessions: 'public/members/sessions'
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get "/members/quit" => "members#quit"
    patch "/members/out" => "members#out"

    devise_scope :member do
      post "members/guest_sign_in" => "members/sessions#guest_sign_in"
    end

    resources :members, only: [:show, :edit, :update] do
      resources :contacts, only: [:new, :show, :create]
    end
    resources :campsites, only: [:index, :show] do
      resources :reviews, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :members, only: [:index, :show, :edit, :update]
    resources :campsites do
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    end
    resources :contacts, only: [:edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :contacts, dependent: :destroy

  has_one_attached:profile_image

  validates :name, presence: true
  validates :name_ruby, presence: true
  validates :nickname, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true

  def self.guest
    find_or_create_by!(name: 'guest' ,email: 'guest@example.com') do |member|
      member.name_ruby = "guest"
      member.nickname = "guest"
      member.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def boolean_label(value)
    value ? '退会' : '有効'
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:is_deleted].present?
      @members = Member.where(is_deleted: params[:is_deleted]).page(params[:page])
      respond_to do |format|
        format.html
        format.js
      end
    else
      @members = Member.page(params[:page])
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member)
    else
      render :edit
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :name_ruby, :nickname, :email, :is_deleted, :profile_image)
  end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_index.html.erb
<div class="row">
  <div class="col">
    <table class="table table-hover">
      <thead>
        <tr class="text-center">
          <th class="col-2">会員ID</th>
          <th class="col-2">会員名</th>
          <th class="col-3">ニックネーム</th>
          <th class="col-3">メールアドレス</th>
          <th class="col-2">会員ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @members.each do |member| %>
        <tr class="text-center">
          <td class="font-weight-bold align-middle"><%= member.id %></td>
          <td class="font-weight-bold align-middle">
            <%= link_to admin_member_path(member), class: "text-dark" do %>
              <%= member.name %>
            <% end %>
          </td>
          <td class="font-weight-bold align-middle"><%= member.nickname %></td>
          <td class="font-weight-bold align-middle"><%= member.email %></td>
          <% if member.is_deleted == false %>
            <td class="text-primary font-weight-bold align-middle">
              <%= member.boolean_label(member.is_deleted) %>
            </td>
          <% else %>
            <td class="text-secondary font-weight-bold align-middle">
              <%= member.boolean_label(member.is_deleted) %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate members, remote: true %>
  </div>
</div>

app/views/admin/members/edit.html.erb
<div style="height: 655px;">
  <div class="container mt-3 mb-3">
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <h1><%= @member.name %>の編集</h1>
        <% if @member.errors.any? %>
          <%= @member.errors.count %>件の記入ミスがあります
          <ul>
            <% @member.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="col"></div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-2"></div>
      <div class="col">
        <%= form_with model:@member, url:admin_member_path(@member) do |f| %>
          <table class="table">
            <tr>
              <th class="border-0 col-2"><%= f.label :profile_image, 'プロフィール画像' %></th>
              <td class="border-0"><%= f.file_field :profile_image, accept: "image/*" %></td>
            </tr>
            <tr>
              <th class="border-0"><%= f.label :name, '名前' %></th>
              <td class="border-0"><%= f.text_field :name, class:"form-control form-control-sm align-middle", style:"width: 200px;" %></td>
            </tr>
            <tr>
              <th class="border-0"><%= f.label :name_ruby, 'フリガナ' %></th>
              <td class="border-0"><%= f.text_field :name_ruby, class:"form-control form-control-sm align-middle", style:"width: 200px;" %></td>
            </tr>
            <tr>
              <th class="border-0"><%= f.label :email, 'メールアドレス' %></th>
              <td class="border-0"><%= f.text_field :email, class:"form-control form-control-sm align-middle", style:"width: 250px;" %></td>
            </tr>
            <tr>
              <th class="border-0"><%= f.label :nickname, 'ニックネーム' %></th>
              <td class="border-0"><%= f.text_field :nickname, class:"form-control form-control-sm align-middle", style:"width: 200px;" %></td>
            </tr>
            <tr>
            <th class="border-0">会員ステータス</th>
              <td class="border-0 font-weight-bold">
                <%= f.radio_button :is_deleted, :false %>
                <%= f.label :is_deleted, "有効", {value: :false} %>
                <%= f.radio_button :is_deleted, :true %>
                <%= f.label :is_deleted, "退会", {value: :true} %>
              </td>
            </tr>
            <tr>
              <td class="border-0"></td>
              <td class="border-0">
                <%= f.submit '変更保存', class: 'btn btn-success mr-4' %>
              </td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<div style="height: 655px;">
  <div class="container mt-3 mb-3">
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <span class="h1">会員一覧</span>
      </div>
      <div class="col">
        <%= form_with(url: admin_members_path, method: :get, data: {remote: true}) do |f| %>
          <span class="font-weight-bold mr-3">退会/有効</span><br>
          <%= f.select(:is_deleted, [['有効', :false], ['退会', :true]], {prompt: '選択'}, class: "form form-control-sm", style:"width: 100px;") %>
          <%= f.submit '表示', class:"btn btn-primary ml-3" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container" id="member-list">
    
            <%= render 'admin/members/index', members: @members %>
          
  </div>
</div>

app/views/admin/members/index.js.erb
$("#member-list").html("<%= j(render 'admin/members/index', members: @members) %>")

app/views/admin/members/show.html.erb
<div style="height: 655px;">
  <div class="container mt-3 mb-3">
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <h1><%= @member.name %></h1>
      </div>
      <div class="col">
        <%= link_to "編集する", edit_admin_member_path(@member), class: "btn btn-success" %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-2">
        <% if @member.profile_image.attached? %>
          <%= image_tag @member.profile_image, size: "200x200", class: "image-fit" %>
        <% else %>
          <%= image_tag asset_path('no_image2.jpg'), size: "200x200" %>
        <% end %>
      </div>
      <div class="col-1"></div>
      <div class="col-5">
        <table class="table">
          <tr>
            <th class="border-0 col-4">会員ID</th>
            <td class="border-0 font-weight-bold"><%= @member.id %></td>
          </tr>
          <tr>
            <th class="border-0">会員名</th>
            <td class="border-0 font-weight-bold"><%= @member.name %>(<%= @member.name_ruby %>)</td>
          </tr>
          <tr>
            <th class="border-0">ニックネーム</th>
            <td class="border-0 font-weight-bold"><%= @member.nickname %></td>
          </tr>
          <tr>
            <th class="border-0">メールアドレス</th>
            <td class="border-0 font-weight-bold"><%= @member.email %></td>
          </tr>
          <tr>
            <th class="border-0">レビュー投稿数</th>
            <td class="border-0 font-weight-bold"><%= @member.reviews.count %></td>
          </tr>
          <tr>
            <th class="border-0">会員ステータス</th>
            <% if @member.is_deleted == false %>
              <td class="border-0 text-primary font-weight-bold align-middle">
                <%= @member.boolean_label(@member.is_deleted) %>
              </td>
            <% else %>
              <td class="border-0 text-secondary font-weight-bold align-middle">
                <%= @member.boolean_label(@member.is_deleted) %>
              </td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>