config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :member, skip: [:passwords], controllers: {
    registrations: "public/members/registrations",
    sessions: 'public/members/sessions'
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get "/members/quit" => "members#quit"
    patch "/members/out" => "members#out"

    devise_scope :member do
      post "members/guest_sign_in" => "members/sessions#guest_sign_in"
    end

    resources :members, only: [:show, :edit, :update] do
      resources :contacts, only: [:new, :show, :create]
    end
    resources :campsites, only: [:index, :show] do
      resources :reviews, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :members, only: [:index, :show, :edit, :update]
    resources :campsites do
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    end
    resources :contacts, only: [:edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campsite.rb
class Campsite < ApplicationRecord

  belongs_to :campsite_type
  belongs_to :prefecture
  has_many :reviews, dependent: :destroy

  has_one_attached :campsite_image
  has_one_attached :map_image
  has_one_attached :temperture_image

  validates :name, presence: true, length: {minimum: 5}
  validates :campsite_type_id, presence: true
  validates :prefecture_id, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, length: {minimum: 7}, numericality: { only_integer: true }
  validates :route, presence: true, length: {minimum: 10}
  validates :feature, presence: true, length: {minimum: 10}
  validates :considerations, presence: true, length: {minimum: 10}

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
end

app/models/campsite_type.rb
class CampsiteType < ApplicationRecord

  has_many :campsites, dependent: :destroy

  enum type_name:{
    "---":0,
    高原:1,海辺:2,河原:3,林間:4,湖畔:5
  }

end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :member

  enum supported_status: {
    unsupported: 0,
    fixed: 1,
  }

  validates :subject, presence: true, length: {maximum: 20}
  validates :demand, presence: true, length: {maximum: 200}

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :contacts, dependent: :destroy

  has_one_attached:profile_image

  validates :name, presence: true
  validates :name_ruby, presence: true
  validates :nickname, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true

  def self.guest
    find_or_create_by!(name: 'guest' ,email: 'guest@example.com') do |member|
      member.name_ruby = "guest"
      member.nickname = "guest"
      member.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def boolean_label(value)
    value ? '退会' : '有効'
  end

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  
  has_many :campsites, dependent: :destroy
  
  enum prefecture_name:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
  
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :campsite
  belongs_to :member
  belongs_to :season

  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps

  #accepts_nested_attributes_for :tagmaps

  has_one_attached:review_image

  validates :title, presence: true, length: { maximum: 30 }
  validates :star, presence: true
  validates :comment, presence: true, length: { maximum: 200 }
  validates :season_id, presence: true

  def save_tags(savereview_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savereview_tags
    new_tags = savereview_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      tagmap = Tag.find_or_create_by(name:new_name)
      self.tags << tagmap
    end
  end

end

app/models/season.rb
class Season < ApplicationRecord
  
  has_many :reviews, dependent: :destroy

  enum season_name:{
    "---":0,
    春:1,夏:2,秋:3,冬:4
  }
  
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tagmaps, dependent: :destroy
  has_many :reviews, through: :tagmaps

  validates :name, presence: true

  scope :merge_reviews, -> (tags){ }

  def self.search_reviews_for(content, method)

    if method == 'perfect'
      tags = Tag.where(name: content)
    elsif method == 'forward'
      tags = Tag.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      tags = Tag.where('name LIKE ?', '%' + content)
    else
      tags = Tag.where('name LIKE ?', '%' + content + '%')
    end

    review_ids = []
    tags.each do |tag|
      review_ids = review_ids + tag.reviews.ids
    end

    return review_ids.uniq

    # tags.inject(init = []) {|result, tag| result + tag.reviews}

  end
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    if params[:supported_status].present?
      @contacts = Contact.where(supported_status: params[:supported_status]).page(params[:page])
      respond_to do |format|
        format.html
        format.js
      end
    else
      @contacts = Contact.page(params[:page])
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:supported_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/campsites_helper.rb
module Admin::CampsitesHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/prefectures_helper.rb
module Admin::PrefecturesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourCamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/cab60e2107.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100 bg-light">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style="background: linear-gradient(#93FFAB, #007700);">
        <div class="container-fluid">
          <a class="navbar-brand p-1" href="/"><%= image_tag('logo.jpg') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if member_signed_in? %>
            <li class="nav-item-name h3 text-light">
              <i class="fa-solid fa-fire-burner text-danger"></i>
              ようこそ、<%= current_member.nickname %>さん！
              <i class="fa-solid fa-fire-burner text-danger"></i>
            </li>
            <li class="nav-item">
              <%= link_to "サイト紹介", about_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", member_path(current_member), class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to 'キャンプ場一覧', campsites_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_member_session_path, method: :delete, class: 'btn btn-primary' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "お問い合わせ一覧", admin_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to "キャンプ場一覧", admin_campsites_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to '会員一覧', admin_members_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-primary' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "サイト紹介", about_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to "キャンプ場一覧", campsites_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_member_registration_path, class: 'btn btn-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_member_session_path, class: 'btn btn-primary' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main style="margin-bottom: 100px;">
      <%= yield %>
    </main>
    <footer class="shadow-sm" style="background: linear-gradient(#007700, #93FFAB); height:100px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-2"></div>
          <div class="col d-flex text-center align-items-center align-middle">
            <h6 class="text-center text-white m-auto">© 2023 fourcamp inc</h6>
          </div>
          <div class="col-2 d-flex align-items-center" style="height:100px;">
            <% if member_signed_in? %>
              <%= link_to "お問い合わせ", new_member_contact_path(current_member), class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>